// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:string,arg2:string):Promise<void>;

export function BrowseLauncherPath():Promise<string>;

export function ConfirmDelete():Promise<boolean>;

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<main.AccountDTO>>;

export function GetAllTranslations():Promise<Record<string, string>>;

export function GetCurrentLanguage():Promise<string>;

export function GetSettings():Promise<main.SettingsDTO>;

export function GetVersion():Promise<string>;

export function QuitApp():Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLauncherPath(arg1:string):Promise<void>;

export function SetStreamerMode(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SwitchAccount(arg1:string):Promise<main.SwitchResultDTO>;
