// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2);
}

export function BrowseLauncherPath() {
  return window['go']['main']['App']['BrowseLauncherPath']();
}

export function ConfirmDelete() {
  return window['go']['main']['App']['ConfirmDelete']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAllTranslations() {
  return window['go']['main']['App']['GetAllTranslations']();
}

export function GetCurrentLanguage() {
  return window['go']['main']['App']['GetCurrentLanguage']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetLauncherPath(arg1) {
  return window['go']['main']['App']['SetLauncherPath'](arg1);
}

export function SetStreamerMode(arg1) {
  return window['go']['main']['App']['SetStreamerMode'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}
